### ISSUE TITLE
Fix "save session" widget and restore to app

### ISSUE THREAD

**Issue by torrin47** [USEPA/EnviroAtlas_JSApp#33]
_From @torrin47 on May 5, 2017 20:44_

Core requirements:

- [x] Layers added to the LayerList widget are saved and restored to that widget
- [x] Custom symbology set for any layer is saved and restored
- [x] Selected Community is saved and restored
- [x] Map Extent is saved and restored
- [x] Local data added via the "Add Data" widget is saved and restored

Anything else? Maybe some future widgets?

_Copied from original issue: Innovate-Inc/EnviroAtlas#467_

**Comment by torrin47** [comment]
_From @Baohong on June 27, 2017 15:3_

Above are the issues to be addressed. I also found two more issues when I tested from my local:
1. After three or four sessions are saved, no new session could be saved. In the log file, there is message: "NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached". We need to explore this problem.
2. One other issue is the graphics saved with session. For example, in Elevation Profile tool, graphics of path could be saved with a session name and the sessions could be downloaded as a file. But when the downloaded file is loaded, profile result could not be recovered even though the graphics of path could be recovered. To recover the profile result would be very complicated. We need to address the graphics issue also.
I will update if more issues are found.

**Comment by torrin47** [comment]
_From @Baohong on June 28, 2017 14:48_

One other feature might be desired for "Save Session" widget: the saved toggle butthon state (on/off) of National/Communities toggle button and the "topics" toggle button in SimpleSearchFilter widget.

**Comment by Baohong** [comment]
I am still working on SaveSession for dynamic layers.
For currently completed tasks, there are several issues need to be discussed:
1. Since PBS checkboxes are dynamically added and SaveSession widget will restore the previously added layers by simulating the click action of the checkboxes. So when user open the SaveSession widget, PBS widget will be open so that all checkboxes in PBS will be avaible for program to access.
2. tiled layer which is corresponding to feature layers in PBS is not working. This issue exist before SaveSession is committed.

**Comment by torrin47** [comment]
Boundary layers are being saved but not restored but otherwise widget seems in good shape, let's test some more to see if we can find any other outliers.
Also outstanding are services added from URL and from AGOL.

**Comment by torrin47** [comment]
Last item to address before production:

> After I’ve loaded a saved session, the first time I try to click on the Ecosystem Services and Biodiversity tab, the filters, etc. are missing. I have to click on one of the other tabs, and then click on the first tab a second time to get it to load. Also, if I load a session with a layer from People and Built Spaces, both the Ecosystem Services & Biodiversity and People and Built Spaces TOC will be empty the first time I click on either of them.
