### ISSUE TITLE
Explore upgrade to WebAppBuilder 2.x

### ISSUE THREAD

**Issue by torrin47** [USEPA/EnviroAtlas_JSApp#38]
_From @torrin47 on June 28, 2017 16:55_

First ask Esri at IUC
Second create blank WebAppBuilder 2.x site and start migrating our widgets over and see what breaks.

_Copied from original issue: Innovate-Inc/EnviroAtlas#587_

**Comment by brosenbaum** [comment]
sounds like it's time to move... https://developers.arcgis.com/web-appbuilder/
