### ISSUE TITLE
Fix title formatting in new popups

### ISSUE THREAD

**Issue by torrin47** [USEPA/EnviroAtlas_JSApp#95]
This is a tiny issue, but want to capture it.  The title in popups seems to run into any of the buttons at the top right - making them non-functional.  The title needs to respect those buttons - css?

![image](https://user-images.githubusercontent.com/2127036/30987628-ad505514-a465-11e7-96f2-b687790aed94.png)

**Comment by brosenbaum** [comment]
Jeremy had played with this a while ago in a different popup (the Description/data fact sheet popup in the search/filter "i"). Maybe it's similar css changes in a different area than the layerlist popup menu?
