### ISSUE TITLE
Small fixes for LayerList widget

### ISSUE THREAD

**Issue by torrin47** [USEPA/EnviroAtlas_JSApp#96]
- [ ] "Turn on/off all layers" works, but the checkmark icons don't get checked/unchecked.
- [ ] "Collapse all layers" actually removes all layers instead
- [ ] Enable Popup menu option should be hidden for EnviroAtlas layers - it conflicts with the popups we have configured. Fine to leave in for other layers.

**Comment by Baohong** [comment]
For item 3, Could we remove "Enable ID Popup" from the dropdown list?

**Comment by torrin47** [comment]
I guess we could remove it for now, since the core EnviroAtlas layers already have popups enabled. It's only relevant for other external layers the user adds. So eventually we probably want it included for certain layers but not others. But this is much lower priority, so it really could make sense to remove it for everything now and put in a ticket to put it back in later.
