### ISSUE TITLE
Popup issues after removing ECAT layer

### ISSUE THREAD

**Issue by brosenbaum** [USEPA/EnviroAtlas_JSApp#97]
Another little issue/bug:
(see attached images) Triplicate “popups” for this layer (and I assume others) after the ECAT tool results are added/removed. 
![ecat1](https://user-images.githubusercontent.com/6422486/31136333-eb64f12e-a835-11e7-8bef-9f3030f098b1.png)
![ecat2](https://user-images.githubusercontent.com/6422486/31136332-eb1c8042-a835-11e7-9f63-0be278fe4b52.png)
![ecat3](https://user-images.githubusercontent.com/6422486/31136334-eb82e06c-a835-11e7-9d78-2cbe0e4f96de.png)

Here are Annie's comments: 
_I am noticing  some funny things with the Identify Tool.  See screen captures below.  App is giving 3 Identify options for one layer and none for second layer.  First two return incorrect value, third returns correct value (see below).  This happened after having run ECAT and removing the layer from Active Layers list.  I think I removed all layers and then added the CRP and GAP status back to the map.  I think the ECAT tool is still messing up Identify._

**Comment by torrin47** [comment]
Believe this is related to the code enabling the popup for ECAT that isn't being disconnected when the ECAT layer is turned off or removed.
